name: azure_ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy<2.0.0
    - pandas
    - tensorflow>=2.15.0
    - keras>=2.15.0
    - mlflow==3.10.1
    - mlflow-skinny==3.10.1
    - azureml-mlflow
    - azure-ai-ml
    - azure-identity
    - azure-mgmt-core
    - yfinance
    - scikit-learn